### ISSUE TITLE
schedule-list.component.html Uncaught (in promise): Template parse errors:

### ISSUE THREAD

**Issue by bravo2bravo3** [chsakell/angular2-features#1]
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Unexpected closing tag "div" (" firstText="&laquo;" lastText="&raquo;" (pageChanged)="pageChanged($event)"></pagination>
</div>  
[ERROR ->]</div>
<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()"): ScheduleListComponent@48:0
zone.js:461 Unhandled Promise rejection: Template parse errors:
Unexpected closing tag "div" (" firstText="&laquo;" lastText="&raquo;" (pageChanged)="pageChanged($event)"></pagination>
</div>  
[ERROR ->]</div>
<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()"): ScheduleListComponent@48:0 ; Zone: angular ; Task: Promise.then ; Value: BaseException$1 {message: "Template parse errors:↵Unexpected closing tag "div…(onClose)="closed()"): ScheduleListComponent@48:0", stack: "Error: Template parse errors:↵Unexpected closing t…dules/@angular/core//bundles/core.umd.js:9091:45)"}message: "Template parse errors:↵Unexpected closing tag "div" (" firstText="&laquo;" lastText="&raquo;" (pageChanged)="pageChanged($event)"></pagination>↵</div>   ↵[ERROR ->]</div>↵<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()"): ScheduleListComponent@48:0"stack: "Error: Template parse errors:↵Unexpected closing tag "div" (" firstText="&laquo;" lastText="&raquo;" (pageChanged)="pageChanged($event)"></pagination>↵</div>   ↵[ERROR ->]</div>↵<modal [animation]="animation" [keyboard]="keyboard" [backdrop]="backdrop" (onClose)="closed()"): ScheduleListComponent@48:0↵    at new BaseException$1 (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:971:27)↵    at DirectiveNormalizer.normalizeLoadedTemplate (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:11937:23)↵    at eval (http://localhost:3000/node_modules/@angular/compiler//bundles/compiler.umd.js:11931:55)↵    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:323:29)↵    at Object.onInvoke (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:9100:45)↵    at ZoneDelegate.invoke (http://localhost:3000/node_modules/zone.js/dist/zone.js:322:35)↵    at Zone.run (http://localhost:3000/node_modules/zone.js/dist/zone.js:216:44)↵    at http://localhost:3000/node_modules/zone.js/dist/zone.js:571:58↵    at ZoneDelegate.invokeTask (http://localhost:3000/node_modules/zone.js/dist/zone.js:356:38)↵    at Object.onInvokeTask (http://localhost:3000/node_modules/@angular/core//bundles/core.umd.js:9091:45)"**proto**: ErrorconsoleError @ zone.js:461_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426
zone.js:463 Error: Uncaught (in promise): Template parse errors:(…)consoleError @ zone.js:463_loop_1 @ zone.js:490drainMicroTaskQueue @ zone.js:494ZoneTask.invoke @ zone.js:426

**Comment by chsakell** [comment]
Indeed there were some breaking changes related to angular/forms, mostly for **ng2-bootstrap**. Apply [these](https://github.com/chsakell/angular2-features/commit/9ffb0c1b6235f5b7d0478b61df24772275bb9f71) changes and it should be fine again.

### ## References:
1. [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap/issues/673)
2. [angular](https://github.com/angular/angular/issues/9230)

Mark the issue as closed if that fixed the errors.

**Comment by bravo2bravo3** [comment]
Thx. !!!!
