### ISSUE TITLE
Not completely updated to @angular/forms

### ISSUE THREAD

**Issue by ericrey85** [chsakell/angular2-features#2]
Code was updated to support @angular/forms but is still using import { FORM_DIRECTIVES, NgForm } from '@angular/common' when this should be changed to '@angular/forms' and omit FORM_DIRECTIVES....see https://angular.io/docs/ts/latest/guide/forms.html

**Comment by chsakell** [comment]
@ericrey85  couldn't completely change to @angular/forms till <i>ng2-datetime</i> plugin [switch](https://github.com/nkalinov/ng2-datetime/issues/24) as well. 
It should be fine now with commmit [372f5d16](https://github.com/chsakell/angular2-features/commit/372f5d16b3bde552dfe6039f1697852f1c3d15c2).

**Comment by ericrey85** [comment]
Thanks a lot Chris, keep up the awesome work !!
