### ISSUE TITLE
Missing Parens on Selectors

### ISSUE THREAD

**Issue by gitonworld** [chsakell/angular2-features#4]
In schedule-edit.component.html missing parens, so changes are not saved!

CHANGED FROM -
select class="form-control" [ngModel]="schedule.status" name="status"
select class="form-control" [ngModel]="schedule.type" name="type"
CHANGED TO +
select class="form-control" [(ngModel)]="schedule.status" name="status"
select class="form-control" [(ngModel)]="schedule.type" name="type"

**Comment by chsakell** [comment]
[#4 closed](https://github.com/chsakell/angular2-features/commit/87a514a2ac3c5cac9fcb09b67165b937e593a7b5)
