### ISSUE TITLE
URL is case sensitive

### ISSUE THREAD

**Issue by skabariya** [chsakell/angular2-features#6]
Hello,

I have clone this app,
When I run this app and if I pass URL route parameter different compare to configured in app.route.ts it will not working.
So what I have to do if I want to check caseInsensitive URL ?

**Comment by chsakell** [comment]
You need a UrlSerializer as follow: 
```javascript
import { DefaultUrlSerializer, UrlTree } from '@angular/router';
// /ref: https://stackoverflow.com/questions/42065409/angular-2-routes-3-0-case-sensitive

export class LowerCaseUrlSerializer extends DefaultUrlSerializer {
    parse(url: string): UrlTree {
        return super.parse(url.toLowerCase());
    }
}
```

And then added it as a provider in the app.module.ts

```javascript
providers: [
  {
     provide: UrlSerializer,
     useClass: LowerCaseUrlSerializer
  }
]
```

I have pushed those changes on the master branch.
