### ISSUE TITLE
traceur 404

### ISSUE THREAD

**Issue by laslo67** [chsakell/angular2-features#8]
Hello. After several days of effort I am unable to make this work. I don't know if it's user error on my end or not but I have followed the simple and straightforward directions that are listed but to no avail. I have done the appropriate investigation and while I've found many issues with similar symptoms I have yet to find something to resolve my issue.  And to be clear I am not making any alterations to the code other than what is required to set the correct API URL. I'm simply trying to get the base repo code to work. And for what it's worth I have tried both the Master and Production branches.

Any assistance would be appreciated.

Details...

* cloned and setup and launched the repo for the backing API for this project (dotnetcore-entityframework-api)
success

* cloned this repo (angular2-features)
success

* npm install
_-- UNMET PEER DEPENDENCY zone.js@0.6.26_

* bower install
success

* updated the api url in config.services.ts api url
this._apiURI = 'http://localhost:8153/api/';

* npm start
browser launched with loading spinner but nothing more

* chrome browser dev tools results
Request URL: http://localhost:3000/traceur
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:3000
initiator: zone.js:1382

**Comment by duanhquy** [comment]
I'm too... and I get lastest some package in systemjs.config.js. I have done , But my code had some error: 
-- Fetch API cannot load npm:plugin-babel.js. URL scheme must be "http" or "https" for CORS request.

please, help me. Thanks pro.

**Comment by chsakell** [comment]
Either stick with the exact **ng2-bootstrap 1.1.5 version** (check [here](https://github.com/chsakell/angular2-features/commit/00e50ea08903b35f7104acdf696ccb87016a0592)) or simply run _git pull_ and _npm install_ to install the latest ng2-bootstrap. I have upgraded the app to its latest version. [upgrade ng2-bootstrap](https://github.com/chsakell/angular2-features/commit/d40d4dfeeaa5691dc80dc1c586fb6dcdfabf37ff)

**Comment by duanhquy** [comment]
Yes! That's best for me. Thank you so much!
